# Generated by Django 2.1.2 on 2018-10-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='RegularEvents',
        ),
    ]
