# Generated by Django 2.1.2 on 2018-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181021_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularevents',
            name='period',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
