# Generated by Django 2.1.2 on 2018-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181021_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='intro_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
